### ISSUE TITLE
Doubt about how to use the extension

### ISSUE THREAD

**Issue by CA10C3SAR** [igorlogius/persistent-element-remover#3]
![image](https://user-images.githubusercontent.com/6724006/103175037-cf223180-4845-11eb-8c7f-8b189108f86c.png)

I see your examples on `example_config.json` but I still did not understand how to insert this element in your extension, could you guide me? 

Thanks

**Comment by igorlogius** [comment]
I'll have to apologize, i seemed to have disabled email notifications. My bad. 
Of course i can try to help you out. If you still need or want help. 
And again. Sorry for the late reply.
