### ISSUE TITLE
[BUG] Possessive RegEx is not recognized as RegEx

### ISSUE THREAD

**Issue by ShockedCoder** [igorlogius/persistent-element-remover#5]
**Describe the bug**
Valid RegEx is not working

**To Reproduce**
1. Add `window.location.href = window.location.href + "/files/all?filter-game-version=2020709689%3A6756"` as the JS code
2. Add `^https?:\/{2}(www\.)?curseforge\.com\/minecraft\/mc-mods\/[-A-z]++(?!#|\/files)` as the RegEx
3. Go to any Curseforge modpage. e.g. [AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin)

**Expected behavior**
For it to match and work

**Additional context**
The problem is the possessive quantifier (++) not working [as intended](https://regex101.com/r/W7edMn/1)

**Comment by igorlogius** [comment]
Yeah, no `++` does not seem to be supported . 
You had the wrong language active. on regex101. 
When you switch to ECMAScript, you get this: 

![snip_20220820-025547](https://user-images.githubusercontent.com/67047467/185723170-6637bfca-fd9a-4556-912c-f17489cb5455.png)
ref. https://regex101.com/
