### ISSUE TITLE
[Setting] Run the code only once

### ISSUE THREAD

**Issue by ShockedCoder** [igorlogius/persistent-element-remover#6]
**Describe the solution you'd like**
A setting so the JS code only runs once.

**Describe alternatives you've considered**
Manually checking for every change, but that would be too inefficient.

**Comment by ShockedCoder** [comment]
How about some labels to indicate which issues are which?

**Comment by igorlogius** [comment]
Sorry for the late reply ... i accidentally switched notifications of for this repo. 

The addon code will only re-run when a page modification has been detected and will only make a modification if the selector is actually found (again). 

The easiest way to achive what you want is to use someting like uBlock Origin ... it has a 
filter/rule set, that only gets apply once.   

Hope this info helps and sorry again for the late reply.
