### ISSUE TITLE
Too many elements are deleted

### ISSUE THREAD

**Issue by JeanGroe** [igorlogius/persistent-element-remover#7]
Sorry, I don't know much about CSS. 
I wanted to delete the "Home" tab of youtube.com, but the CSS selector "ytd-guide-section-renderer.style-scope:nth-child(1) > div:nth-child(2) > ytd-guide-entry-renderer:nth-child(1)" deletes the other tabs too. Why does this happen?

**Comment by igorlogius** [comment]
Sorry for the late reply ... i seemed to have mistakenly switched of notifications for this repository, but i'll take a look at your issue now.

**Comment by igorlogius** [comment]
Well, it seem like, that after removing the first element 
The next one ... also matches the selector. :-D 

Luckily PER also supports Javascript. 
This rule, gets the job done: 
[per-export-youtube-remove-home.txt](https://github.com/igorlogius/persistent-element-remover/files/9385952/per-export-youtube-remove-home.txt)
